main:
  web_trigger_proxy_build:
    - services:
        - docker
      imports: https://cnb.cool/4baco/secrets/-/blob/main/docker-envs.yml
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:$var1"
          exports:
            info: IMAGE_TAG
        - name: build
          script: docker buildx build --provenance=false -t $IMAGE_TAG -f ./AIProxy.Proxy/Dockerfile ./

        - name: push
          script: docker push $IMAGE_TAG